name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Specify the Java distribution
          java-version: '21'     # Specify the Java version

      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}  # Use the predefined GitHub token
